package cloudflavor:skyforge@0.1.0;

interface plugin-api {
    record config {
        name: string
    }

    enum error {
        invalid-format,
        missing-field,
        other,
    }

    deserialize-config: func(config-str: string) -> result<config, error>;
}

world skyforge-api {
    export plugin-api;
}